version: "3"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./csv_files:/csv_files # Mount your CSV file directory
    ports:
      - 5432:5432

  flask_app:
    build: ./flask_app  # Assuming your Flask application code is in a directory named "flask_app"
    restart: always
    ports:
      - 5000:5000  # Expose the port on which your Flask app runs
    depends_on:
      - db  # Ensure that the Flask app service depends on the database service
    environment:
      DATABASE_URL: postgresql://username:password@db:5432/database
      FLASK_ENV: development
    volumes:
      - ./flask_app:/app

